---
title: "Datos de felinos de Costa Rica"
author: "Andrea Padilla"
date: '2022-06-08'
output: 
  html_document:
    code_folding: hide
    theme: readable
    toc: true
    toc_depth: 5
    toc_float:
      collapsed: false
      smooth_scroll: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Introducción


## Herramientas de desarrollo

### Paquetes de R


```{r carga-paquetes, message=FALSE}
```


```{r carga-paquetes, message=FALSE}
library(sf)
library(dplyr)
library(leaflet)
library(ggplot2)
library(plotly)
library(DT)
```

```{r datos}
provincias <- # objeto sf de datos vectoriales con geometrías de multipolígonos
  st_read(
    "C:/Users/gf0604-1/datos geoespaciales/clase 08-06-22/provincias.geojson", # archivo de datos de entrada
    quiet = TRUE
  ) %>%
  st_transform(4326) # transformación al sistema de coordenadas WGS84
```


```{r carga-paquetes, message=FALSE}
```

```{r}
felinos <-
  st_read(
    "C:/Users/gf0604-1/datos geoespaciales/clase 08-06-22/felinos.csv",
    options = c(
      "X_POSSIBLE_NAMES=decimalLongitude", # columna de longitud decimal
      "Y_POSSIBLE_NAMES=decimalLatitude"   # columna de latitud decimal
    ),
    quiet = TRUE
  ) 

 st_crs(felinos)<-4326
```

# Tabla

```{r Tabla, echo=FALSE}
# Visualización de datos de felinos en formato tabular
felinos %>%
  dplyr::select(species,
                eventDate,
                stateProvince,
                locality,
                decimalLongitude,
                decimalLatitude) %>%
  st_drop_geometry() %>%
  datatable(
    colnames = c(
      "Especie",
      "Fecha",
      "Provincia",
      "Localidad",
      "Longitud",
      "Latitud"
    ),
    options = list(
      pageLength = 10,
      language = list(url = '//cdn.datatables.net/plug-ins/1.10.11/i18n/Spanish.json')
    )
  )
```

# Gráfico
```{r gráfico, message=FALSE, echo=FALSE}
grafico_felinos <-
  felinos %>%
  count(species) %>%
  ggplot(aes(x = reorder(species, n), y = n)) +
  geom_bar(stat = "identity") +
  ggtitle("Cantidad de felinos") +
  xlab("Cantidad") +
  ylab("Felinos") +
  coord_flip() + #cambiar ejes
  theme_minimal()

ggplotly(grafico_felinos)

```

# Mapa
```{r}
leaflet() %>%
  addTiles() %>% # capa de base OSM
  # addPolygons(
  #   data = provincias,
  #   color = "black",
  #   fillColor = "transparent",
  #   stroke = TRUE,
  #   weight = 1.0,
  # ) %>%
  addCircleMarkers( # capa de registros de presencia (puntos)
    data = felinos, 
    stroke = F,
    radius = 4, 
    fillColor = "blue",
    fillOpacity = 1
    )
```
```{r}

```

